### PR TITLE
Coding Out Search Service - WIP & for review

### PR DESCRIPTION
**Pull request by tobiaswest83**
## Issue 59 - WIP!!!

This is my WIP for #59. I am interested in feedback on 
1. approach so far
2. further enhancements 
3. other things people would like to see in the returned object (looking at you @mike-morrison :-)) 

This is *not* intended to be a final release, it's really just for others to review my approach. I have tried to ensure that the properties exposed match the properties available in the API (including settings defaults, where they are defined in the API). 

There are a few exceptions, `SelectProperties` for example is a string in the GET API, but as a consumer it would make for a poor experience if they have to type "Title,Author", better for them to build an array, as shown below. 

### Usage

To use this in the browser, build as documented and (assuming you have a SharePoint page set up) run the following in the console. You'll also be able to better examine the returned object

```javascript
var s = pnp.sharepoint.rest.web.search;
s.QueryText = "test"
// s.SelectProperties = ["Title", "Author", "Byline"]

s.getSearchResults().then(function(data){
    console.log(data);
;});

```

This returns the following

```json
{
   "RawSearchResults":"THEACTUALRESULTSFROMSHAREPOINT",
   "PrimarySearchResults":[
      {
         "Title":"Test",
         "Author":"Tobias West",
         "Byline":"This is the article byline!"
      },
     {
         "Title":"Test 2",
         "Author":"Tobias West",
         "Byline":"This is the article 2 byline!"
      },
   ]
}
}
```

### TODO

- write tests, ensure code coverage is appropriate document
- handle more advanced scenarios in the returned data set, such as paging, grouping, SecondaryQueryResults etc. 
- handle POST @patrick-rodgers  I was considering whether `Queryable` should have a public post method which processes the same `query` collection to build the POST body, thoughts?
- Sort object & implementation
- A few other, rarely used properties which I need to R&D more. 

### Final notes

There are a few files in the PR I shouldn't have included, but since we're not integrating I'm not too worried about that. The final PR would be tidy with appropriate commit messages :)

### CODE REVIEW

**Comment by mike-morrison** [comment]
> (assuming you have a SharePoint page set up)

I do not?  What type of page is this?

**Comment by patrick-rodgers** [comment]
Nice start @tobiaswest83, a few comments:

- Probably need to do a pull as we have updated the syntax to pnp.sp.web.* based on feedback in last week's call.
- What about a syntax that would do something like pnp.sp.web.search({ obj }).get().then(...)? That obj could be a strongly typed search configuration interface that would have properties like query text, etc and would allow things to chain a little smoother. You would then return a new Search(this) that is configured based on the passed in settings. Moving the logic from the getSearchResults, which you then don't need. Let me know if this makes sense, if not I can do a quick example.
- I don't want to publically expose post() because not everything can be posted so it breaks the fluent interface. Take a look at webs.ts for examples of using post inside methods to match actions and return a promise.

Again, great start!

**Comment by tobiaswest83** [comment]
Hey @patrick-rodgers, thanks for feedback!

- Will do a pull sure
- I did think about creating a strongly typed `SearchQuery` class but decided against it, I can't remember my reasoning so I'll switch over to that approach! :)
- Take your point on POST, to that end pnp.sp.web.search would need to take `SearchQuery` and an optional `Boolean` for usePOST, which defaults to false, happy with that approach?

I'll crack on with this tonight, might have a proper PR ready tomorrow depending on how the creation of test scripts goes.

**Comment by mike-morrison** [comment]
Looking really good.  It would be cool if it returned the totalcount <-- It's not completely worthless when paging/threading, but it almost is.  totalcount should be total search hits and it's a moving target.

ElapsedTime metadata field would also be cool.

What would be really cool is to have a search builder that looked something like this:
````

SearchQuery
  .rowLimit(20)
  // Intellisense for SearchFields.  This would avoid having to know them or look them up.
  .select(SearchFields.author, SearchFields.byLine, SearchFields.custom('ad-prop')) 
  .xxxxxxx()
  .getResults();

````

Also is it feasible to return the results like this?
````
"PrimarySearchResults":[
      {
         "Title":"Test",
         "Author":"Tobias West"
         "Byline":"This is the article byline!"
      },
     {
         "Title":"Test 2",
         "Author":"Tobias West"
         "Byline":"This is the article 2 byline!"
      },
   ]
````

Definitely looking good!

**Comment by tobiaswest83** [comment]
yo @mike-morrison, thanks for feedback. I can add those properties into `SearchResult`

As we're splitting out `Search` and `SearchQuery`, I don't think we can create a builder, and I'm not sure JS supports that kind of syntax? I'd also say that building a `SearchField` class wouldn't be that useful. I can't think of a way to dynamically build that from existing Managed Properties and a static enum would be basic (and I don't fancy typing out RefinableString01 -> RefinableString199 :smile:)

Re the results, that is how they're returned - I just got my JSON syntax wrong in the post above - great spot. 

Thanks for the feedback :+1:

**Comment by patrick-rodgers** [comment]
One thing to keep in mind is sticking to the fluent API syntax we are trying to develop. Also, I believe the only difference between GET and POST is to accommodate queries that would be too long for a standard URL? You could perhaps auto detect that and choose get/post accordingly - or just always do post.

You could look at supporting something like:

`pnp.sp.web.search({ query object}).then(...);`

So inside the search fire off the request and not require an additional call. For that query object you can have a simple interface, which will provide intellisense in the editor and prescribe the options. So a full call might be something like:

`pnp.sp.web.search({ 
rowLimit: 20,
select: ["field1", "field2"],
...,
}).then(function(parsedResults) { ... })`

**Comment by tobiaswest83** [comment]
There are a couple of other circumstances, but these are being obfuscated from the user. 

Do I remember you saying that cross site-collection calls are handled appropriately? If so, I see no harm in us using POST all the time.

**Comment by mike-morrison** [comment]
````
export namespace Search {
	export class SearchFields {
		static Author: string = "Author";
		static ByLine: string = "ByLine";
		static SearchText: string = null;
		static SelectFields: string = null;

		// Microsoft Excel Generated this code so I only had to write the first line and a formula.  

		static RefinableString01: string = "RefinableString01";
		static RefinableString02: string = "RefinableString02"
		static RefinableString03: string = "RefinableString03"
		static RefinableString04: string = "RefinableString04"
		static RefinableString05: string = "RefinableString05"
		static RefinableString06: string = "RefinableString06"
		static RefinableString07: string = "RefinableString07"
		static RefinableString08: string = "RefinableString08"
		static RefinableString09: string = "RefinableString09"
		static RefinableString10: string = "RefinableString10"
		static RefinableString11: string = "RefinableString11"
		static RefinableString12: string = "RefinableString12"
		static RefinableString13: string = "RefinableString13"
		static RefinableString14: string = "RefinableString14"
		static RefinableString15: string = "RefinableString15"
		static RefinableString16: string = "RefinableString16"
		static RefinableString17: string = "RefinableString17"
		static RefinableString18: string = "RefinableString18"
		static RefinableString19: string = "RefinableString19"
		static RefinableString20: string = "RefinableString20"
		static RefinableString21: string = "RefinableString21"
		static RefinableString22: string = "RefinableString22"
		static RefinableString23: string = "RefinableString23"
		static RefinableString24: string = "RefinableString24"
		static RefinableString25: string = "RefinableString25"
		static RefinableString26: string = "RefinableString26"
		static RefinableString27: string = "RefinableString27"
		static RefinableString28: string = "RefinableString28"
		static RefinableString29: string = "RefinableString29"
		static RefinableString30: string = "RefinableString30"
		static RefinableString31: string = "RefinableString31"
		static RefinableString32: string = "RefinableString32"
		static RefinableString33: string = "RefinableString33"
		static RefinableString34: string = "RefinableString34"
		static RefinableString35: string = "RefinableString35"
		static RefinableString36: string = "RefinableString36"
		static RefinableString37: string = "RefinableString37"
		static RefinableString38: string = "RefinableString38"
		static RefinableString39: string = "RefinableString39"
		static RefinableString40: string = "RefinableString40"
		static RefinableString41: string = "RefinableString41"
		static RefinableString42: string = "RefinableString42"
		static RefinableString43: string = "RefinableString43"
		static RefinableString44: string = "RefinableString44"
		static RefinableString45: string = "RefinableString45"
		static RefinableString46: string = "RefinableString46"
		static RefinableString47: string = "RefinableString47"
		static RefinableString48: string = "RefinableString48"
		static RefinableString49: string = "RefinableString49"
		static RefinableString50: string = "RefinableString50"
		static RefinableString51: string = "RefinableString51"
		static RefinableString52: string = "RefinableString52"
		static RefinableString53: string = "RefinableString53"
		static RefinableString54: string = "RefinableString54"
		static RefinableString55: string = "RefinableString55"
		static RefinableString56: string = "RefinableString56"
		static RefinableString57: string = "RefinableString57"
		static RefinableString58: string = "RefinableString58"
static                 RefinableString1XX = "...";
		static RefinableString167: string = "RefinableString167"
		static RefinableString168: string = "RefinableString168"
		static RefinableString169: string = "RefinableString169"
		static RefinableString170: string = "RefinableString170"
		static RefinableString171: string = "RefinableString171"
		static RefinableString172: string = "RefinableString172"
		static RefinableString173: string = "RefinableString173"
		static RefinableString174: string = "RefinableString174"
		static RefinableString175: string = "RefinableString175"
		static RefinableString176: string = "RefinableString176"
		static RefinableString177: string = "RefinableString177"
		static RefinableString178: string = "RefinableString178"
		static RefinableString179: string = "RefinableString179"
		static RefinableString180: string = "RefinableString180"
		static RefinableString181: string = "RefinableString181"
		static RefinableString182: string = "RefinableString182"
		static RefinableString183: string = "RefinableString183"
		static RefinableString184: string = "RefinableString184"
		static RefinableString185: string = "RefinableString185"
		static RefinableString186: string = "RefinableString186"
		static RefinableString187: string = "RefinableString187"
		static RefinableString188: string = "RefinableString188"
		static RefinableString189: string = "RefinableString189"
		static RefinableString190: string = "RefinableString190"
		static RefinableString191: string = "RefinableString191"
		static RefinableString192: string = "RefinableString192"
		static RefinableString193: string = "RefinableString193"
		static RefinableString194: string = "RefinableString194"
		static RefinableString195: string = "RefinableString195"
		static RefinableString196: string = "RefinableString196"
		static RefinableString197: string = "RefinableString197"
		static RefinableString198: string = "RefinableString198"
		static RefinableString199: string = "RefinableString199"
		
		static RowLimit = 500;
	}

	export class Builder {
		constructor(query: string) {
			Search.SearchFields.SearchText = query;
		}

		selectProperties(props: string[]) {
			SearchFields.SelectFields = props.join(",");
			return this;
		}
		
		rowLimit(numRows: number) {
			SearchFields.RowLimit = numRows;
			return this;
		}
		
		toString() {
			document.getElementsByTagName('button')[0].textContent = `RowLimit = ${SearchFields.RowLimit}!\nSelectProps = ${SearchFields.SelectFields}`;
		}
	}
}


let fields = Search.SearchFields;
let b = new Search.Builder("SharePoint 2013");




let button = document.createElement('button');
button.textContent = "toString()";
button.onclick = function () {
	b
		.selectProperties([fields.Author, fields.ByLine, fields.RefinableString42])
		.rowLimit(20)
		.toString();
}

document.body.appendChild(button);

```

![image](https://cloud.githubusercontent.com/assets/6625993/14799095/82500878-0b00-11e6-9149-a3e6c5641b68.png)

**Comment by mike-morrison** [comment]
FYI, Not saying that is a good idea by any means.  Just demonstrating the concept.

**Comment by mike-morrison** [comment]
I personally would prefer to consume this using the @patrick-rodgers solution above with the intellisense on the object.  I prefer that over chaining by a long shot.

**Comment by tobiaswest83** [comment]
Cool, I'm working to that approach. I won't be mapping out a SearchField interface, it will be unwieldy and seldom used IMO - almost all projects I've been involed in require us creating custom content types and/or using an alias against refiners. 

@patrick-rodgers feel free to close this - I think I've got some great feedback!

**Comment by patrick-rodgers** [comment]
Ok, I'll close this one - look forward to what you come up with!

**Pull request closed without merging**
