### PR TITLE
Split types

### LINKED ISSUE #68: Split types.ts
Should we split the interfaces in types.ts to own files?

Usage of type is now ```import * as Types from "./types";``` will have to become ```import { Type } from "./types/type.ts";```

### PR DESCRIPTION
**Pull request by pbjorklund**
Resolves #68

(Rebased version, gh doesn't seem to like that so can't reopen #77)

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Is this ready to be merged? Based on the issue it appears there was more work pending?

**Comment by pbjorklund** [comment]
Yes, give me a few days to get caught up and I can start chewing off the todo-items in #68.

Sorry for the delay

**Comment by patrick-rodgers** [comment]
All good, just checking to see if it was ready.

**Comment by patrick-rodgers** [comment]
Going to close this PR for now, can always be re-opened or resubmitted as needed. Thanks!

**Pull request closed without merging**
