### PR TITLE
Temporary fix for gulp-header bug

### PR DESCRIPTION
**Pull request by mike-morrison**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | reported via gitter
#### What's in this Pull Request?

Fixes temporary build issue caused by a [gulp-header bug](https://github.com/tracker1/gulp-header/issues/36)

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
So the issue is with gulp-header and the fix is to make sure were are up to a newer version? Just want to make sure I understand what happened and that it wasn't something we did. Though odd I don't see it - so I must have still a version from before this bug was introduced in gulp-header. Sound right?

**Comment by mike-morrison** [comment]
I fixed the link to the issue in the gulp-header repo.  The issue is they introduced a bug in the latest version which we pull during npm install.  1.8.3 so we temporarily need to hardcode directly to 1.8.2 until they merge the fix and release an update.  They apparently broke a lot of folk's repos.  The only thing we could have done differently is to specify a specific version instead of letting it pull the most recent update.

**Comment by s-KaiNet** [comment]
Yes, it looks like you said. Right after `npm install` I'm having the latest `gulp-header 1.8.3`, which has a bug. You should be able to reproduce the issue by deleting folder `node_modules/gulp-header` and running `npm install` to restore `1.8.3` version.

**Comment by patrick-rodgers** [comment]
Got it, ok - nice work finding this. I'll go ahead and merge into dev. If you could track the bug on their side we can update back to latest once they get it sorted out.

**Pull request merged**
