### PR TITLE
Initial design for Issue #132

### PR DESCRIPTION
**Pull request by olemp**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    |  yes
| New sample?      | no 

#### What's in this Pull Request?

Initial design for Issue #132

### CODE REVIEW

**Comment by olemp** [comment]
@patrick-rodgers This is the initial design for pnp.taxonomy. Would love some feedback.

**Comment by patrick-rodgers** [comment]
Hi Ole,

Here are my comments in no particular order:

1. I think taxonomy should live under sp and not directly at the root as it deals with sharepoint taxonomy. We may one day deal with other things so I think keeping things grouped will eventually pay off.
2. This relies on SP.* files, similar to my comment in #135 perhaps we can look at a way to ensure they are loaded? Not sure what the best path is there, but something to consider. Applies to provisioning as well. At a minimum we need to document the dependencies.
3. isValidGUID comments needs updated
4. We have been consolidating the files for example both items and item live in the items.ts file, could do the same here to reduce the total number of files. (termsets & termset could be in termsets.ts)
5. For the resolve in get in terms.ts would it be good to resolve with the object(s)? That would follow the pattern we've used else where, and I think you can type the Promise to make it easy for folks to see what is happening.

Great start so far look forward to getting this cleaned up and part of the library.

**Comment by olemp** [comment]
Good input. Reason behind 1 is that sp is currently a new instance of Rest, and I didn't want to put Taxonomy under Rest. Let's find a way to solve this.

I'll have a look at your comments and will update the PR this week.

**Comment by patrick-rodgers** [comment]
Ah, I see. Ok, yes, let's think about it. Perhaps we can do something with declaration merging to create an sp that isn't just a new Rest instance.

**Comment by olemp** [comment]
@patrick-rodgers Updated the PR with fixes for 3, 4 and 5.

1 and 2 requires some more discussion. 

1. You said it above. I'll have a look.
2. We need to find the nicest way to make sure SP.Taxonomy is defined when we need it.

Right now it's done in taxonomysession.ts

`EnsureSPTaxonomy(): Promise<any> {
        return new Promise((resolve, reject) => {
            if (SP.hasOwnProperty("Taxonomy")) {
                resolve();
            } else {
                SP.SOD.registerSod("sp.taxonomy.js", `${_spPageContextInfo.siteAbsoluteUrl}/_layouts/15/sp.taxonomy.js`);
                SP.SOD.registerSodDep("sp.taxonomy.js", "sp.js");
                SP.SOD.executeFunc("sp.taxonomy.js", "TaxonomySession", resolve);
            }
        });
    }`

But would be nice to have a global util or so, that makes sure it's defined by loading the needed scripts.

**Comment by olemp** [comment]
1. SharePoint.ts which merges Rest and Taxonomy?

**Comment by patrick-rodgers** [comment]
Yes a files that represents SP makes sense, just need to make sure we maintain the pnp.sp.web syntax we've been using.

**Comment by olemp** [comment]
@patrick-rodgers Something like

_sharepoint.ts_
`
import { Taxonomy } from "./taxonomy/taxonomy";
import { Rest } from "./rest/rest";
import { Util } from "../../utils/util"; 

const rest = new Rest();
const taxonomy = new Taxonomy();

export const SharePoint = Util.extend(rest, { taxonomy: taxonomy });
`

**Comment by olemp** [comment]
#2: What about a method on web/site, @patrick-rodgers? 

`web.ensureNamespace("SP.Taxonomy")`

`web.ensureNamespace("sp.taxonomy.js")`

which used SP.SOD.registerSod, SP.SOD.executeFunc, ExecuteOrDelay etc etc.

**Comment by patrick-rodgers** [comment]
I'd like to avoid taking a dependency in web on the SP.* libs if possible. Sorry didn't know this was waiting on input from me.

**Comment by patrick-rodgers** [comment]
This seems to have gone inactive - going to close for now, please do reopen when ready! Thanks!

**Comment by jonathanhotono** [comment]
Any news for this feature? This would be a valuable feature for spfx webparts.

**Pull request closed without merging**
