### PR TITLE
First draft of learning roadmap

### PR DESCRIPTION
**Pull request by pbjorklund**
Created a draft of a learning roapmap.

But now I'm thinking that perhaps it should be in the wiki instead, but I had no access.

Thoughts?

Do you like the structure?
Is it the right things?
Relevant links?
Useful?

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
This is a great start, thanks - I agree this would be great wiki content. I created the first page of the wiki, does that now allow you to add pages? If not can take a look and see if I need to mess with permissions.

**Comment by pbjorklund** [comment]
Does indeed look like I have no access to edit the wiki.

**Comment by patrick-rodgers** [comment]
So this is interesting. The only options are to allow anyone with push access to edit wikis, or let anyone in the world edit them. I have enabled full edit for public, please let me know if that works for you. If so we'll have to see how that goes with public edit turned on.

**Comment by pbjorklund** [comment]
Added it as a wiki page https://github.com/OfficeDev/PnP-JS-Core/wiki/Learning-roadmap
Also updated the main wiki with a table of contents.

Should we perhaps move some of the checked in .md to the wiki?

**Comment by patrick-rodgers** [comment]
Closing as this was added to Wiki

**Pull request closed without merging**
