### PR TITLE
Add locale enum

### PR DESCRIPTION
**Pull request by pbjorklund**
Created based on discussion from #64

### CODE REVIEW

**Comment by pbjorklund** [comment]
Not sure if it belongs in /collections.. Thoughts?

**Comment by tobiaswest83** [comment]
Thanks @patrick-rodgers, saves me a job!

Think it doesn't fit in /collections since it's just an enum

what about /types (new folder)?

**Comment by patrick-rodgers** [comment]
I vote for just adding it to types.ts. That file is getting huge so we could look at adding a folder and breaking it up - though they aren't really used other than as refs so in the end it doesn't matter too much.

**Comment by tobiaswest83** [comment]
Too late Patrick, Patrik has picked this up :-)



On Mon, Apr 25, 2016 at 10:50 AM -0700, "Patrick Rodgers" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #67<https://github.com/OfficeDev/PnP-JS-Core/pull/67> to @tobiaswest83<https://github.com/tobiaswest83>.

-

**Comment by pbjorklund** [comment]
Moved it to a new types folder.

**Comment by patrick-rodgers** [comment]
Thanks Patrik (man one of these days I am going to put the "c" in there, you'll have to forgive me :) )

**Pull request merged**
