### PR TITLE
Updated package.json to point at compiled ES5 in dist

### PR DESCRIPTION
**Pull request by mike-morrison**
Fixes npm package by pointing main to ES5.

### CODE REVIEW

**Comment by mike-morrison** [comment]
Actually just realized it might make more sense to just compile lib to es5+commonjs, but not concatenate the files.  So we can do import {getRandomString} from 'pnp/rest/sharepoint/util/util'.  Thoughts?

**Comment by patrick-rodgers** [comment]
Thanks Mike, but this doesn't work when you try and consume the npm package modified in this way within a ts project. The result is the below error, which is why I had packaged the lib folder and associated .d.ts files separately based on [this thread](https://github.com/Microsoft/TypeScript/issues/7872)

`Exported external package typings file 'c:/test/node_modules/sp-pnp-js/dist/pnp.d.ts' is not a module. Please contact the package author to update the package definition.`

**Comment by mike-morrison** [comment]
@patrick-rodgers That is what I meant by my comment above about leaving the files loose.  The files should stay loose and in lib, but they need to be transpiled to ES5.  http://node.green/ <-- shows es2015 features supported by node.  Looks like we will still need to transpile lib to es5 for some time.  I will update the PR.

**Comment by mike-morrison** [comment]
We can't point the main for the NPM package at ES6 though.  Node and Browsers aren't there yet.  It has to be ES5.  Without it, you get a bunch of errors like "import" being an invalid symbol in environments that don't support all of the same ES6 constructs, which is none of them AFAIK.

**Comment by patrick-rodgers** [comment]
I am going to close this. I have updated the package -> lib to target es 5. Both of these import syntaxes are support and work in my testing with this update:

import pnp from "sp-pnp-js";

import { objectIsNull } from "sp-pnp-js/lib/utils/args";

**Pull request closed without merging**
