### PR TITLE
pnp\sp\provisioning: start(), need to resolve the first promise

### PR DESCRIPTION
**Pull request by olemp**
| Q               | A
| --------------- | ---
| Bug fix?        | Yes
| New feature?    | No
| New sample?      | No
| Related issues?  |

#### What's in this Pull Request?

Fixing a Promise bug in pnp\sp\provisioning

### CODE REVIEW

**Comment by olemp** [comment]
(On another note, @patrick-rodgers, I will soon add some documentation on usage, with some sample JSON templates)

**Comment by olemp** [comment]
Added a few other bugfixes to this same PR. They're all in provisioning.

Didn't want to mess up the PR system with serveral PRs for minor fixes.

**Comment by patrick-rodgers** [comment]
Thanks - I haven't had time to test the provisioning at all so appreciate you taking a look.

**Comment by olemp** [comment]
No worries. Would love to start using this version instead of the original in customer projects soon!

**Pull request merged**
