### PR TITLE
Move all tests to /tests, move schema from .d.ts to .ts, add gulp task for building tests, change location of compiled sources

### PR DESCRIPTION
**Pull request by pbjorklund**
Moved all test files into /tests folder.

Added build-tests gulp task (do we need lint-tests as well perhaps?)

### Questionable move 1 
Don't know why the files in src/sharepoint/provisioning/schema were.d.ts files. They make more sense as normal ts interfaces to me.

Went from ```/// <reference path="ihiddenview.d.ts" />``` to ```import { IHiddenView } from "../schema/ihiddenview";```

Due to this I also deleted schema.d.ts

Please advice if this is a bad idea.

### Questionable move 2
Made tests build to /lib/tests and src to /lib/src for references to stay valid in tests. Src and tests can now be built separately which is the main benefit.

### Questionable move 3
Use ```export default class PnP {``` instead of ```export = PnP``` to use ```import pnp from "../src/pnp";``` in pnp.tests.ts

### CODE REVIEW

**Comment by pbjorklund** [comment]
Note: I do not know if this affects any other gulp task, npm packaging or things like that. Help me out by testing it :)

Here's an interesting way to check out a PR locally

Add
```fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*```
to .git/config under (I assume you have your fork as origin remote and OfficeDev as upstream)
```[remote "upstream"]```
and do a git fetch (edited)

now you can check out this pull requests locally with
```git checkout upstream/pr/62```

**Comment by tobiaswest83** [comment]
@pbjorklund I'll check that out today, while I'm working on #59. I've been seeing some weird behavior with the gulp tasks which I've yet to look at which your PR may go some way to helping.

**Comment by patrick-rodgers** [comment]
Thanks @pbjorklund, I will take a look at this today. Responses to your questions:

1. This is how it was added by the developer at the time. I noted it but haven't had time to work on provisioning pieces as they aren't priority currently. I think making them .ts files is the correct move.
2.  This has likely broken package and serve gulp tasks as they depended on the folders, but I will test.
3.  Unsure on this one, those two syntaxes should have resulted in the same behavior. Will also need to test this out with the package.

**Comment by patrick-rodgers** [comment]
I had to make a few changes to fix package and the resulting pnp.js file. Turns out we need export = PnP as that lets it all work once "built". I updated the pnp.test.ts file to import the library using this syntax, which resolves the import issue: import pnp = require("../src/pnp");. Going to merge my change in a separate PR to maintain the contributor attribution.

**Pull request merged**
